// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    MapBox: typeof import('./src/components/MapBox.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    PropForm: typeof import('./src/components/PropForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side: typeof import('./src/components/Side.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    ToolsFloat: typeof import('./src/components/ToolsFloat.vue')['default']
    UiContainer: typeof import('./src/components/UiContainer.vue')['default']
  }
}
